language: rust

cache: cargo

before_script:
    - rustup component add rustfmt

rust:
    - beta
    - stable

script:
    - cargo fmt --all -- --check
    - cargo build -v
    - cargo test -v
    - cargo doc -v
